# Generated by Django 3.1.3 on 2020-11-12 14:55

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Product',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title1', models.CharField(max_length=200)),
                ('text1', models.TextField()),
                ('title2', models.CharField(max_length=200)),
                ('text2', models.TextField()),
                ('title3', models.CharField(max_length=200)),
                ('text3', models.TextField()),
                ('title4', models.CharField(max_length=200)),
                ('text4', models.TextField()),
                ('title5', models.CharField(max_length=200)),
                ('text5', models.TextField()),
                ('title6', models.CharField(max_length=200)),
                ('text6', models.TextField()),
                ('title7', models.CharField(max_length=200)),
                ('text7', models.TextField()),
                ('size1', models.TextField()),
                ('size2', models.TextField()),
                ('size3', models.TextField()),
                ('size4', models.TextField()),
                ('size5', models.TextField()),
                ('color1', models.TextField()),
                ('color2', models.TextField()),
                ('color3', models.TextField()),
                ('color4', models.TextField()),
                ('color5', models.TextField()),
                ('cover1', models.ImageField(upload_to='images/')),
                ('cover2', models.ImageField(upload_to='images/')),
                ('cover3', models.ImageField(upload_to='images/')),
                ('cover4', models.ImageField(upload_to='images/')),
                ('cover5', models.ImageField(upload_to='images/')),
                ('cover6', models.ImageField(upload_to='images/')),
                ('cover7', models.ImageField(upload_to='images/')),
                ('cover8', models.ImageField(upload_to='images/')),
                ('cover9', models.ImageField(upload_to='images/')),
                ('cover10', models.ImageField(upload_to='images/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Post',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Order',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.TextField()),
                ('phone', models.TextField()),
                ('size', models.TextField()),
                ('color', models.TextField()),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
        migrations.CreateModel(
            name='Feedback',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(max_length=200)),
                ('text', models.TextField()),
                ('cover', models.ImageField(upload_to='images/')),
                ('created_date', models.DateTimeField(default=django.utils.timezone.now)),
                ('published_date', models.DateTimeField(blank=True, null=True)),
                ('author', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
